# Generated by Django 2.1.7 on 2019-03-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("phone_no", models.CharField(max_length=10)),
                ("street", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=2)),
                ("postal_code", models.CharField(max_length=6)),
                ("country", models.CharField(max_length=20)),
            ],
        )
    ]
