# Generated by Django 2.1.7 on 2019-03-23 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("doctors", "0002_auto_20190317_0445")]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"permissions": (("doctor", "Allow doctor users only"),)},
        )
    ]
