# Generated by Django 2.1.7 on 2019-03-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("doctors", "0002_auto_20190312_1945")]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="user_id", new_name="user"
        )
    ]
