# Generated by Django 2.1.7 on 2019-03-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("doctors", "0003_auto_20190323_0126")]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "permissions": (
                    ("isdoctor", "Allow doctor users only"),
                    ("is_doctor_of_patient", "Allow only patient's assigned doctor"),
                )
            },
        )
    ]
