# Generated by Django 2.1.7 on 2019-03-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("doctors", "0004_auto_20190323_1436")]

    operations = [migrations.AlterModelOptions(name="profile", options={})]
