# Generated by Django 2.1.7 on 2019-03-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("patient_id", models.IntegerField()),
                ("bp_systolic", models.IntegerField()),
                ("bp_diastolic", models.IntegerField()),
                ("heart_rate", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("created_on", models.IntegerField()),
            ],
        )
    ]
