# Generated by Django 2.1.7 on 2019-03-17 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
                ('dob', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('contact_firstname', models.CharField(max_length=20)),
                ('contact_lastname', models.CharField(max_length=20)),
                ('contact_relationship', models.CharField(max_length=20)),
                ('contact_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bp_systolic', models.IntegerField()),
                ('bp_diastolic', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('height', models.CharField(max_length=6)),
            ],
        ),
    ]
