# Generated by Django 2.1.7 on 2019-03-12 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("patients", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="patient_profile",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
