# Generated by Django 2.1.7 on 2019-03-13 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_auto_20190313_0013"),
        ("patients", "0002_auto_20190312_1945"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="user_id", new_name="user"
        ),
        migrations.RenameField(
            model_name="record", old_name="user_id", new_name="user"
        ),
        migrations.RemoveField(model_name="profile", name="doctor_id"),
        migrations.AddField(
            model_name="profile",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctors.Profile",
            ),
        ),
    ]
