# Generated by Django 2.1.7 on 2019-03-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("patients", "0003_auto_20190313_0013")]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
